// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwqwdkmkjljamusfzhhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3cXdka21ramxqYW11c2Z6aGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTAzODYsImV4cCI6MjA2MDU2NjM4Nn0.fOquWzlN42UtO15225ONeCAS5ROtSYKvEgxprfALMew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);